baseURL = "https://uofcdess.netlify.com"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Digital Engineering Students' Society | DESS"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.footer]]
URL = "about"
name = "About"
weight = 1
[[menu.footer]]
URL = "project"
name = "Our Team"
weight = 2
[[menu.footer]]
URL = "service"
name = "Digital Minor"
weight = 3
[[menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "project"
name = "Our Team"
weight = 2
[[menu.main]]
URL = "service"
name = "Digital Minor"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4
[[menu.main]]
hasChildren = true
name = "Pages"
weight = 5
[[menu.main]]
URL = "faq"
name = "FAQ"
parent = "Pages"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[params]
author = "Digital Engineering Students' Society"
contact_form_action = "#"
description = "This is meta description"
email = "uofcdess@gmail.com"
google_analitycs_id = ""
location = "2500 University Dr NW, Calgary, AB T2N 1N4"
logo = "images/Logo_banner_white_text.jpg"
mobile = "N/A"
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.0776"
map_longitude = "114.1407"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Contact Us"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ion-social-instagram-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "https://ca.linkedin.com/in/digital-engineering-students-society-0847b319b"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "https://www.facebook.com/UofC.DESS/"
