---
label: Team
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
  description: this is meta description
- type: file
  name: image
  label: image
- type: file
  name: bg_image
  label: bg image
  description: page header background image
- type: field_group_list
  name: information
  label: information
  fields:
  - type: text
    name: label
    label: label
  - type: text
    name: info
    label: info
  config:
    labelField: label
  hidden: false
pages:
- exampleSite/content/english/project/president.md
- exampleSite/content/english/project/vp-academic-copy.md
- exampleSite/content/english/project/vp-academic.md
- exampleSite/content/english/project/vp-communications.md
- exampleSite/content/english/project/vp-events.md
- exampleSite/content/english/project/vp-finance-and-operations.md
